### ISSUE TITLE
How to access remote Docker private registry

### ISSUE THREAD

**Issue by arjunm183** [BradleyA/Search-docker-registry-v2-script.1.0#5]
The script which you provide has to be executed in the host where docker registry is deployed.

Is there a way to access remote docker private registry on v2.

Api doesnt work for me

**Comment by BradleyA** [comment]
No, it has to be executed on a system that includes the filesystem where the images are stored.  I use NFS to mount the image filesystem on any host I need to run the script.  You could use the ssh command to run a command on a remote host:
ssh uthree@192.168.1.203 ' /usr/local/bin/view-private-registry'

Hope that helps.

**Comment by arjunm183** [comment]
I understand thats the way of accessing it by mounting the file system over nfs.
What if i have some 50 nodes and i have to mount using autofs or nfs which consumes network bandwidth and again an administration of this..
I understand your script clearly, however do you have any idea on calling remote api instead of mounting directory over nfs on all the clients.

**Comment by BradleyA** [comment]
Here is a script that can access the view-private-registry script remotely from any of your 5000 nodes.  It includes the ssh command line in my earlier response.
I am running a Docker Swarm cluster with Docker 1.12r5.  I only start my containers on the cluster manager nodes which have the  mounted NFS registry V2 filesystem.

**Comment by BradleyA** [comment]
Hope that answered your question, Not hearing back from you I am closing the incident.  Feel free to reopen if you need to.
