### ISSUE TITLE
docker registry setup and IP SANs

### ISSUE THREAD

**Issue by mramanathan** [BradleyA/Search-docker-registry-v2-script.1.0#8]
Hi Bradley,

Pls excuse for opening a new issue unrelated to this repo. This was the only way to contact you.

Recently, I hit upon this IP SANs issue (https://github.com/docker/distribution/issues/948) and wanted to know few things. You have outlined what you did to get over this; however, am stumbled inspite of following the procedure.

Is there a way to contact you (mail or skype) to talk ?

/Ram

**Comment by BradleyA** [comment]
Sorry I just now saw this.   My email address is allen.bradley@ymail.com.  
Feel free to reopen
